export function getAssistantLoadingMessage(): string {
  const messages: string[] = [
    "Certo, deixa eu buscar isso para você...",
    "Ok, estou analisando os dados agora.",
    "Só um instante, já estou verificando.",
    "Deixe comigo, estou consultando as informações.",
    "Estou processando sua solicitação.",
    "Aguarde um momento, estou analisando.",
    "Já estou trabalhando nisso para você.",
    "Um segundo, estou organizando os dados.",
    "Estou cruzando as informações agora.",
    "Deixe-me verificar isso rapidamente.",
    "Estou consultando as fontes disponíveis.",
    "Só um instante enquanto analiso.",
    "Estou validando os dados agora.",
    "Analisando os pontos relevantes...",
    "Estou preparando a resposta para você.",
    "Buscando as melhores informações...",
    "Já estou estruturando os resultados.",
    "Processando os dados solicitados...",
    "Estou revisando os detalhes.",
    "Verificando as informações disponíveis...",
    "Organizando os dados neste momento.",
    "Estou consolidando as informações.",
    "Só um momento enquanto verifico isso.",
    "Estou analisando os parâmetros.",
    "Consultando os registros relevantes...",
    "Estou avaliando os dados agora.",
    "Certo, iniciando a análise.",
    "Deixe-me conferir isso para você.",
    "Estou revisando os dados disponíveis.",
    "Analisando os resultados encontrados...",
    "Preparando a resposta ideal para você.",
    "Processando sua consulta.",
    "Estou verificando as correspondências.",
    "Buscando as informações mais relevantes.",
    "Organizando os dados coletados...",
    "Estou examinando os detalhes agora.",
    "Aguarde um instante enquanto analiso.",
    "Já estou verificando isso.",
    "Consultando os dados em tempo real...",
    "Estou estruturando a melhor resposta.",
    "Analisando cuidadosamente as informações.",
    "Validando os registros disponíveis...",
    "Estou cruzando múltiplas fontes.",
    "Processando os critérios informados...",
    "Estou interpretando os dados agora.",
    "Verificando os resultados obtidos...",
    "Organizando a resposta para você.",
    "Estou preparando os insights relevantes.",
    "Conferindo as informações solicitadas...",
    "Só mais um momento, já retorno."
  ];

  const randomIndex = Math.floor(Math.random() * messages.length);
  return messages[randomIndex];
}
